[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/kanagawa-wave.toml"
]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 13.0

[font.bold]
family = "SauceCodePro Nerd Font Propo"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font Propo"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Propo"
style = "Regular"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0
command = { program = "osascript", args = ["-e", "beep"] }

[window]
decorations = "buttonless"
dynamic_padding = false
startup_mode = "Windowed"
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 120
lines = 40
